version: '3'
services:
  testrunner:
    build: .
    working_dir: /go/src/github.com/nghialv/localjet
    volumes:
      - .:/go/src/github.com/nghialv/localjet
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.4.3